# Generated by Django 4.0.4 on 2022-07-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_alter_flights_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=5)),
                ('flights', models.ManyToManyField(blank=True, related_name='passenger', to='flights.flights')),
            ],
        ),
    ]
