# Generated by Django 4.0.4 on 2022-07-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='seat_available',
            field=models.IntegerField(default=200),
        ),
    ]
